# Generated by Django 3.1.1 on 2020-09-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinfo',
            name='completed',
        ),
    ]
