# Generated by Django 3.1.1 on 2020-09-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_info_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='mothers_name',
        ),
    ]
