# Generated by Django 3.1.1 on 2020-09-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_taskinfo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='completed',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=255),
        ),
    ]
