# Generated by Django 3.1.1 on 2020-09-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_taskinfo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='completed',
            field=models.BooleanField(max_length=255, null=True),
        ),
    ]
