# Generated by Django 3.1.1 on 2020-09-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200923_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='completed',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
    ]
