# Generated by Django 3.1.1 on 2020-09-22 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20200922_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
