# Generated by Django 3.1.1 on 2020-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200917_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='deadline',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
