# Generated by Django 3.1.1 on 2020-09-17 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_taskinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
