# Generated by Django 3.1.1 on 2020-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200917_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
