# Generated by Django 3.1.1 on 2020-09-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200922_1507'),
        ('main', '0011_auto_20200917_1535'),
    ]

    operations = [
    ]
